stages:
  - build
  - test
  - deploy

.db:
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby/
      policy: pull
  variables:
    POSTGRES_DB: openproject_test
    POSTGRES_USER: openproject_test
    POSTGRES_PASSWORD: ''
    POSTGRES_HOST_AUTH_METHOD: trust
    RAILS_ENV: test
    DISABLE_SPRING: 1
  services:
    - postgres:latest
  before_script:
    - bin/gitlab_ci/setup_db

build:
  extends: .db
  stage: build
  cache:
    - key: ${CI_JOB_NAME}
      paths:
        - frontend/.npm/
      when: on_success
      policy: pull-push

    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby/
      policy: pull-push

    - paths:
        - apt-cache/
  script:
    - bin/gitlab_ci/compile_assets

  artifacts:
    paths:
      - public/assets/
      - public/javascripts/
      - frontend/src/locales/
      - frontend/src/app/features/plugins/
      - config/frontend_assets.manifest.json

include:
  - project: openproject/XmlImport
    ref: feature/improve_ci
    file: .gitlab-ci-tests.yml
