stages:
  - build
  - staging

default:
  image: ruby:3.1.2
  cache:
    paths:
      - vendor/ruby/
    policy: pull
  before_script:
    - ruby -v
    - bundle config set --local path 'vendor/ruby'
    - bundle install -j $(nproc)

#services:
#  - postgres:latest

build:
  stage: build
  cache:
    - key: ${CI_JOB_NAME}
      paths:
        - frontend/.npm/
        - frontend/node_modules/
      when: on_success
      policy: pull-push

    - paths:
        - apt-cache/
  before_script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - apt-get update -qq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -yqq nodejs npm
  script:
    - cd frontend && npm ci --cache .npm --prefer-offline
    - npm run build
  artifacts:
    paths:
      - public/

deploy-to-stage:
  stage: staging
  needs:
    - job: build
      artifacts: true
  script:
    - ls public
