stages:
  - build
  - test

.db:
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby/
      policy: pull
  variables:
    POSTGRES_DB: openproject_test
    POSTGRES_USER: openproject_test
    POSTGRES_PASSWORD: ''
    POSTGRES_HOST_AUTH_METHOD: trust
    RAILS_ENV: test
    DISABLE_SPRING: 1
  services:
    - postgres:latest
  before_script:
    - bundle config set --local path 'vendor/ruby'
    - bundle install -j $(nproc)

    - mv config/database.yml.example config/database.yml
    - "echo '  host: postgres' >> config/database.yml"
    - "echo '  schema_dump: false' >> config/database.yml"
    - bundle exec rails db:migrate

build:
  extends: .db
  stage: build
  cache:
    - key: ${CI_JOB_NAME}
      paths:
        - frontend/.npm/
      when: on_success
      policy: pull-push

    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby/
      policy: pull-push

    - paths:
        - apt-cache/
  script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - apt-get update -qq && apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -yqq nodejs npm
    - cd frontend && npm ci --cache .npm --prefer-offline
    - cd ..
    - bundle exec rails assets:precompile
  artifacts:
    paths:
      - public/assets/
      - public/javascripts/
      - frontend/src/locales/
      - frontend/src/app/features/plugins/
      - config/frontend_assets.manifest.json
