stages:
  - build
  - test
  - deploy

include:
  - project: openproject/XmlImport
    ref: feature/improve_ci
    file:
      - gitlab_ci/.gitlab-ci-tests.yml
      - gitlab_ci/.gitlab-ci-deploy.yml

  - local: gitlab_ci/.gitlab-ci-deploy-template.yml

.db:
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby/
      policy: pull
  variables:
    POSTGRES_DB: openproject_test
    POSTGRES_USER: openproject_test
    POSTGRES_PASSWORD: ''
    POSTGRES_HOST_AUTH_METHOD: trust
    RAILS_ENV: test
    DISABLE_SPRING: 1
  services:
    - postgres:latest
  before_script:
    - bin/gitlab_ci/setup_db

build:
  extends: .db
  stage: build
  cache:
    - key:
        files:
          - frontend/package-lock.json
      paths:
        - frontend/.npm/

    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby/

    - paths:
        - apt-cache/
  script:
    - echo $CI_JOB_TRIGGERED
    - bin/gitlab_ci/compile_assets

  artifacts:
    paths:
      - public/assets/
      - public/javascripts/
      - frontend/src/locales/
      - frontend/src/app/features/plugins/
      - config/frontend_assets.manifest.json

deploy-openproject-stage:
  needs:
    - job: build
      artifacts: true
  rules:
    - if: $CI_JOB_TRIGGERED != "true"
  extends: .deploy-template
  script:
    - scp build.zip $SSH_OPENPROJECT_USER@$VM_STAGE_ADDRESS:/home/openproject/openproject
    - ssh $SSH_OPENPROJECT_USER@$VM_STAGE_ADDRESS bash -s < bin/gitlab_ci/deploy_script
